baseURL: "https://erickwan2014.github.io/learning-journey/"
title: Eric's Learning Journey
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Eric's Learning Journey
  description: Eric's Learning Journey
  author: Eric

  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # home-info mode
  homeInfoParams:
    Title: "Welcome to visit my learning journey"
    Content: >
      "I think, fundamentally, open source does tend to be more stable software. It's the right way to do things." — Linus Torvalds

  socialIcons:
    - name: github
      url: "https://github.com/EricKwan2014"

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
